apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: {{ namespace }}
spec:
  valuesContent: |-
    controller:
      config:
        hsts: "false"
    tcp:
      5432: {{ namespace }}/reportdb:5432
      4505: {{ namespace }}/salt:4505
      4506: {{ namespace }}/salt:4506
      25151: {{ namespace }}/cobbler:25151
      9100: {{ namespace }}/tomcat:9100
      # Comment if installed with server-helm.enableMonitoring = false
      5556: {{ namespace }}/taskomatic:5556
      5557: {{ namespace }}/tomcat:5557
      9187: {{ namespace }}/db:9187
      9800: {{ namespace }}/taskomatic:9800
      ## Only if installed with server-helm.exposeJavaDebug = true
      # 8001: {{ namespace }}/taskomatic:8001
      # 8002: {{ namespace }}/search:8002
      # 8003: {{ namespace }}/tomcat:8003
    udp:
      69: {{ namespace }}/tftp:69
