name: CI validation tests

on:
  pull_request:
    branches:
      - master

jobs:
  validate_salt:
    name: Validate Salt states
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      with:
        fetch-depth: 1
#    - uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40 #v1.4.3
#      with:
#        packages: salt-common
#        version: 1.0
#        execute_install_scripts: true
    - name: Install Salt using bootstrap
      run: |
        curl -fsSL https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh -o install_salt.sh
        sudo sh install_salt.sh -P -x python3
    - name: Validate server states
      if: always()
      run: bash .github/workflows/ci-validation/salt-server-validation
    - name: Validate client states
      if: always()
      run: bash .github/workflows/ci-validation/salt-client-validation
    - name: Validate minion states
      if: always()
      run: bash .github/workflows/ci-validation/salt-minion-validation
    - name: Validate controller states
      if: always()
      run: bash .github/workflows/ci-validation/salt-controller-validation
    - name: Validate mirror states
      if: always()
      run: bash .github/workflows/ci-validation/salt-mirror-validation
    - name: Validate containerized server states
      if: always()
      run: bash .github/workflows/ci-validation/salt-server-containerized-validation

  validate_opentofu_config:
    name: Validate opentofu configuration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      with:
        fetch-depth: 1
    - uses: opentofu/setup-opentofu@e95ccdd20623115bfd7d47df14a3250d6066a9d0 #v1.0.7
      with:
        tofu_version: 1.10.7
    - name: Validate configuration using example files
      run: .github/workflows/ci-validation/opentofu-validation

  validate_terraform_config:
    name: Validate terraform configuration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      with:
        fetch-depth: 1
    - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd #v3.1.2
      with:
        terraform_version: 1.6.0
    - name: Validate configuration using example files
      run: .github/workflows/ci-validation/terraform-validation
